### ISSUE TITLE
[Tooltip] Tooltip sticks on the screen when clicking on the target's element, which is added dynamically

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1094]
## Description

`Tooltip` sticks on the screen when clicking on the target's element, which is added dynamically.

## Steps to Reproduce

1. Go to this [CodeSanbox](https://codesandbox.io/s/uui-tooltip-sticky-tooltip-issue-qvjokh?file=/example.tsx)
2. Make sure "X" icon next to the text in the button is not visible
3. Hover over the button and make sure a tooltip is displayed
4. Click on the button and make sure the "X" icon is displayed next to the text in it
5. Move cursor away from the button - the tooltip hides, which is correct, because trigger is set to "hover"
6. Hover over the button again and click on it to display the "X" icon
7. Click on the "X" icon this time and move cursor away from the button

## Actual result

The tooltip sticks on the screen.

Before clicking on the "X" icon:

![image](https://user-images.githubusercontent.com/10310491/223342204-04a4bd59-8a19-474f-ba1a-b734936f6a8a.png)

After clicking on the "X" icon:

![image](https://user-images.githubusercontent.com/10310491/223341996-cc423948-8e72-4d10-bb7a-9e926b52e2a4.png)

## Expected result

The tooltip hides.

## Environment

* UUI version: 4.6.3 (with React 17.0.2), 4.10.1-beta.1 (with React 18.2.0, see the CodeSandbox in the "Steps to Reproduce" section)
* Browser name: Google Chrome v.110.0.5481.178
* Operating System: Windows 10 64-bit

## Notes

There is a workaround in the latest of the mentioned versions: set `closeOnMouseLeave` to `boundary` in the `Tooltip` component, but I still think the component should work without it.

**Comment by EpamFanAnton** [comment]
Hi @vasilii-kovalev, 

After some investigation, it was found that the issue seems to be browser behavior.

If you click on the element inside the button that will disappear after, it will not propagate `onMouseLeave` event.

If you provided the example case, can you please provide the real one where you found this issue? Maybe we will be able to get around this problem.

**Comment by vasilii-kovalev** [comment]
Hello, @EpamFanAnton. The example I provided in the CodeSandbox is the same, as we use in our product. Though it has different styles, it has the same behavior. Its purpose is filtering the data in a table. If it is disabled (not clicked on), it doesn't have the "X" icon (since it is unnecessary). When it is enabled, the icon appears so that the user can disable the filter.

**Comment by AlekseyManetov** [comment]
Sorry, but i still don't clearly understand you case, may be you can share some screenshots or videos of current behavior? 
From UX perspective, if you have a button with cross icon, by clicking on this icon whole button should be removed , so the tooltip will be unmounted and disappeared.

**Comment by vasilii-kovalev** [comment]
> Sorry, but i still don't clearly understand you case, may be you can share some screenshots or videos of current behavior? From UX perspective, if you have a button with cross icon, by clicking on this icon whole button should be removed , so the tooltip will be unmounted and disappeared.

No, in our case, clicking on the "X" icon only switches off this particular button, which is a representation of a filter option.
IMO, enabled/disabled state of filter options can be reflected only by a color change, without showing/hiding the "X" icon, and should be changed when clicking on the whole button. But:
1. Maybe there are best practices, which say, that color coding is not enough, and the icon should be presented to more clearly highlight the available action. I will ask our UX designer
2. There may be cases, where just removing the problematic element is impossible, because it plays an important role. In this case, the issue would still need fixing

**Comment by AlekseyManetov** [comment]
> But the tooltip listens to the first child's (target's) events (which it attaches ref to, and which is the button in our case), not its (the button's) children, isn't it?

Yes, but in this case, the event didn't bubble up to the button node, possibly because this node was already removed, and the link with the parent node was destroyed(I'm not sure about the reasons for this behavior). So, the `onMouseLeave` event fired on the icon but not on the button.

Overall, this case seems to be an edge case and rare, so there we don't want to implement any complex hacks to fix it. Perhaps you can find a UX solution to this issue? I'm not sure, but having control that disappears from the user by some action is also not a good pattern. Maybe you can replace this icon with another one that does, instead of show/hide it?

**Comment by vasilii-kovalev** [comment]
We decided to wait until the `Tag` component is updated, which will suit our needs, and get rid of this appearing/disappearing "X" icon. Clicking on the whole component will change the state, and the background/foreground color will reflect the current state value.
Closing the issue.
