### ISSUE TITLE
[MainMenuAvatar] Component should be button

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#1104]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description
[Cloud Codesandbox](https://codesandbox.io/p/sandbox/mainmenuavatar-as-a-button-s4tyv6?file=%2Fsrc%2FExample.test.tsx). Re-run **test** task to see failed tests.

## Steps to Reproduce

1. Render `MainMenuAvatar` component

## Actual result

Component rendered as non-focusable non-interactive `<div>` element

## Expected result

Component rendered as focusable interactive `<button>` element

## Environment

* UUI version: 4.10.1
* Browser name: FF 110.0.1
* Operating System: Ubuntu 20.04

**Comment by vasilii-kovalev** [comment]
Why is this component should be a button and not just an image? In our case, we don't need it to be interactive. Can the "button" behavior be opted-out?

**Comment by Sushasgit** [comment]
Hi @vasilii-kovalev, will discuss this question with @AlekseyManetov, because it seems to be a interactive element which is clickable. And it should be a `button` according to WAI ARIA recommendation( https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions/). And this will require from us implement changes. Will get back with an updates, thanks!

**Comment by Sushasgit** [comment]
Hi, after discussion - we won't add make this component as a button for now. Because this is valid case when this component won't be interactive and can include only image as in comment above. 
We'll add `role` button for it - only if prop `onClick` is exist and tab index. Further improvements regarding accessibility will be made in the next iteration. Thanks!

**Comment by cpof-tea** [comment]
> We'll add `role` button for it - only if prop `onClick` is exist and tab index. Further improvements regarding accessibility will be made in the next iteration. Thanks! 

Okay, but please, check that focusable `<div>`'s `onClick` will be triggered with native `<button>` behaviour (via `Enter` or `Space`)

**Comment by AlekseyManetov** [comment]
I suppose that `MainMenuAvatar` should always be a `<button>` tag without any configuration, because only one reason to use `MainMenuAvatar` it's a case when you need to make it interactive or dropdown toggler. For simple cases when you need to just display avatar image, it's better to use `Avatar` component directly.

**Comment by NatalliaAlieva** [comment]
Released in 5.0.0 ver.
