### ISSUE TITLE
[RTE] incorrect highlighting(color) link after copy from other places

### ISSUE THREAD

**Issue by nadiushkaNA** [epam/UUI#1167]
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
**1. a link doesn't have "sky" color**

https://user-images.githubusercontent.com/11243577/228493929-3ad8aa4b-dcae-4e2b-ad90-b51777a3bd45.mp4

**2. a URL doesn't understand as a link**

1) https://www.atlassian.com/agile/scrum/scrum-metrics#:-text=What9620are%20scrum%20metrics963F.improve%20a%20team's%20agile%20journey
2) https://github.com/epam/UUI

https://user-images.githubusercontent.com/11243577/228495393-5347f745-b9ee-4392-9892-90c5403a2e78.mp4

## Expected result

links detected and has "sky" color

**Comment by NatalliaAlieva** [comment]
1. In your example, the link is colored in purple because it has been previously visited. We have decided to improve this behavior: in the "Edit" mode, all links will be colored in blue, but when switching to the "View" mode, previously visited links will be colored in purple. This case has been moved to [improvement №1177](https://github.com/epam/UUI/issues/1177).
2. This case has been moved to [issue №542](https://github.com/epam/UUI/issues/542) (case №3), as it collects bugs related to copying/pasting links.
