### ISSUE TITLE
[ArrayListView][AsyncListView]: sorting of elements when a search is applied.

### ISSUE THREAD

**Issue by Kuznietsov** [epam/UUI#1239]
## Idea
As it is mentioned in the [original issue](https://github.com/epam/UUI/issues/612), it is required to provide the functionality for sorting elements while searching.

## To be done:
- Pass `search` argument to `sortBy` function, which will give the possibility to implement the `matching` prioritizing of the results.
- Add the default implementation of the prioritization algorithm for `ArrayListView` and `AsyncListView`.

**Comment by jakobz** [comment]
Suggestions:

- I'd like to avoid having two different algorithms - one for search (```f(search) => (text) => boolean```), and one for ranking (```f(search) => (text) => number```). These two can be combined, by making ```getSearchFilter``` to return a number instead of boolean. The number is a ranking score, higher-ranked records would be displayed first.

- we can add a similar API for users to hook into search directly. E.g. additionally to the existing ```getSearchFields?(item: TItem): string[];```, we can allow passing a lower-level function like ```applySearch(item: TItem): boolean | number```, where number is a ranking used to search. The boolean is left for cases when users don't need ranking.

- for both default, and user-defined applySearch, we can use returned rank as an implicit 1st level of sorting. Therefore, if user's defined applySearch returns boolean for all records, the 2nd sorting will be applied, leading to the same sorting as normal, w/o search. This would also allow our default implementation to apply 2nd level default sorting for the equally ranked items.

**Comment by NatalliaAlieva** [comment]
Released in 5.1.1 ver.
