### ISSUE TITLE
[Button]: Add more flexible types for rawProps

### ISSUE THREAD

**Issue by RealOneReal** [epam/UUI#1421]
## Now
IHasRawProps<React.ButtonHTMLAttributes<HTMLButtonElement>>
## To Do
Like a :
IHasRawProps<React.ButtonHTMLAttributes<HTMLButtonElement | HTMLAnchorElement>>
## Describe the solution you'd like (optional)
I want to change rel attribute for Button with prop target='_blank' ( I use rawProps) and now I have a trouble with types for rawProps.
Or maybe you can add prop rel to Button  :)

**Comment by AlekseyManetov** [comment]
We can't use such type like: `React.ButtonHTMLAttributes<HTMLButtonElement | HTMLAnchorElement>`, because it will be the union of both types and only similar properties will be in the result. 
Anyway, which value you want to provide for the `rel` attribute? By default we are setting `noopener noreferrer` value for it, if ` target='_blank' `was passed, and i guess it's only one valid value for such case.

**Comment by AlekseyManetov** [comment]
As a workaround you can cast rawProps type to any, e.g.: 
            `<Button  caption="Primary Action" rawProps={ { rel: 'referrer' } as any } />`
Because, unfortunately, in current implementation, it's impossible to support both type for button and for anchor.

**Comment by AlekseyManetov** [comment]
release in 5.4.2 version
