### ISSUE TITLE
[SearchInput] "Maximum call stack size exceeded" error spam in console with still working persistent focus

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1433]
## Description

When implementing persistent focus for `SearchInput` component (that is set again once the input loses focus), I can see "Maximum call stack size exceeded" error spam in console while the component is still working without any problems.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-search-input-persistent-focus-issue-msnsj4?file=/example.tsx)
2. Open the example in a new window/tab (embedded view doesn't show errors for some reason)
3. Click somewhere on the page: input, tabs, tabs content, white area around – doesn't matter
4. Open DevTools and check the console

## Actual result

~9 errors "Maximum call stack size exceeded" per click appear in the console.

## Expected result

Either (or combination of) of these:
* Actually throw the error. It seems the component handles the error itself, because even without `ErrorHandler` wrapping the `Example` component, everything is still working
* If the described implementation is incorrect, a correct one is suggested
* No spam in console, since the component still work when the errors appear. It affects both the issues static, collected by monitoring system, and the console itself, hiding really important problems

## Environment

* UUI version: 4.10.0, 5.0.0
* Browser name: Google Chrome v.114.0.5735.134
* Operating System: Windows 11 64-bit

## Notes

* Probably other inputs are affected too, not only `SearchInput`
* Persistent focus is necessary for user's convenience. In our case, the provided example is a widget of searching people among the tabs. Each tab is a group of people. So when user types in something and clicks on a tab, it is convenient to keep the focus on the input to be able to change the search string

**Comment by AlekseyManetov** [comment]
I have investigated these errors and observed that there is a loop in the React event handlers. It is possible that there is a race condition between the blur and focus events or some other issue. However, based on the call stack, this loop is not caused by UUI code.

As a workaround, I suggest returning focus to the input element inside the TabButton click handler. You can find an example in the CodeSandbox provided: [link to CodeSandbox](https://codesandbox.io/s/uui-search-input-persistent-focus-issue-forked-p4nzv9?file=/example.tsx).

**Comment by vasilii-kovalev** [comment]
Thank you for the investigation and reply!
I think we can implement the second solution. The first one assumes that clicks are performed on tab buttons only, but they can be performed on anything within the widget, and it would be hard to support all the possible cases.
Closing the issue.

**Comment by AlekseyManetov** [comment]
I'm not sure about the reasons, i didn't investigate it much. Maybe it because we have program focus in TextInput component. We capture focus events on div container and then call  `inputElement.current?.focus();` to focus nested input, may be this behaviour caused loop in your case. 
Anyway, i'm not sure that we need to investigate it more and fix, because your case very tricky and looks like a hack and i guess it will take a lot of time to go deeper and understand what is the reason. I guess that proposed solution is suitable for your case.

I'm not entirely certain about the exact reasons behind this issue as I haven't investigated it a lot. It's possible that the loop is occurring because we use program focus in `TextInput` component. We capture focus events on the `div` container and then use inputElement.current?.focus() to focus the nested input. This behavior may be causing the loop in your specific case.

However, addressing this complex and unique case would require significant investigation and time investment and the future solution won't be worth it due to its complexity(we we wouldn't want to rewrite the component to support this case). Considering it, it may be more practical to proceed with the proposed solution, which seems suitable for your specific needs.

**Comment by vasilii-kovalev** [comment]
The actual problem was the `ref`, passed to the component, is not assigned to the input, but to its container (a `div` element).
There is a mess with `ref`-s [here](https://github.com/epam/UUI/blob/main/uui/components/inputs/TextInput.tsx#L51-L53). Maybe you'd want to review this code.
That's our current workaround solution:
```typescript
const ref = useRef(null);

const onBlur = () => {
  if (ref.current !== null) {
    /*
      For some reason, the `ref` is not assigned to the input, but its
      wrapper instead, so we need to get it manually.
      To avoid dependency on exact input's location in the DOM tree
      (because UUI team can change it at any time),
      we use `querySelector`.
    */
    const inputElement = ref.current.querySelector(
      "input[type=\"search\"]",
    );

    if (inputElement !== null) {
      // @ts-expect-error the method actually exists.
      inputElement.focus();
    }
  }
};

return (
  <SearchInpit
    onBlur={onBlur}
  />
);
```

**Comment by AlekseyManetov** [comment]
> The actual problem was the ref, passed to the component, is not assigned to the input, but to its container (a div element).

The current implementation of our refs always points to the root node of the component, so there are no issues with that. If we were to pass the ref directly to the input element, it would limit access to the wrapper, which could be required in certain scenarios, such as positioning dropdowns or tooltips.
