### ISSUE TITLE
[PickerInput] can't show only selected 

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#147]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

PickerInput with the attribute, for instance, minCharsToSearch={ 1 } should show selected items after click "Show only selected"

# Current Behavior

https://user-images.githubusercontent.com/17798957/129361748-db145f7a-c883-49a2-8795-09cf3965754c.mov

## Steps to Reproduce

Use PickerInput in the selectionMode="multi" and minCharsToSearch={ 1 } and try to click "Show only selected"

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

UUI version: 4.1.1
Browser name: Chrome 92.0.4515.131
Operating System: MacOS Big Sur V.11.4

**Comment by jonybekov** [comment]
Is it still a problem?

**Comment by KathrineMatveeva** [comment]
Yes, Show only selected  switcher doesn't work when use props in such combination:   searchPosition="input" minCharsToSearch>0.  May be it is possible to hide this switcher?

**Comment by AlekseyManetov** [comment]
Hi, it still an problem in such variation of props and we have no good solution for it. `minCharsToSearch` and 'Show only selected'  has conflicting logic - we need to reset search by toggling, because we can't perform search for only selected items and also `PickerInput` need some search string to show body when `minCharsToSearch` is passed.

In latest release we add `hideShowOnlySelected` prop for `DataPickerFooter` component, so you can easily disable this toggle for this case by passing `renderFooter` prop into `PickerInput`:
`renderFooter = (footerProps) => <DataPickerFooter { ...footerProps } size='36' hideShowOnlySelected={ true } />`
