### ISSUE TITLE
[Dropdown]: Click event inside dropdown body is propagated to the target

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1629]
## Description

Click event inside a dropdown body is propagated to the target, causing unintended behavior. For example, if a target is a cell of an expandable row in a table, and has a dropdown opening on hover, clicking inside the dropdown's body leads to the row expanding/collapsing.

## Steps to Reproduce

1. Go to this [CodeSandbox](https://codesandbox.io/s/uui-dropdown-propagated-click-from-body-to-target-issue-grc4gk?file=/Example.tsx)
2. Hover over any name in "Name" column
3. Click inside the appeared dropdown body

## Actual result

The row with the name is expanded (if was collapsed) or collapsed (if was expanded).

## Expected result

The event shouldn't be propagated to the target. In this case, nothing should happen.

## Notes

The workaround is to wrap the dropdown body element in a `div`, add click handler and call `event.stopPropagation` inside it. Like this:

```typescript
renderBody={(bodyProps) => {
  return (
    <div
      onClick={(event) => {
        event.stopPropagation();
      }}
    >
      <DropdownMenuBody {...bodyProps}>
        <Text>Click on this text</Text>
      </DropdownMenuBody>
    </div>
  );
}}
```

But adding this is rather annoying. Creating an abstraction may be a fine temporary solution, but would be great to fix on the library's side or at least provide a property to ignore propagation to `Dropdown` and/or body components.

## Environment

* UUI version: 5.1.2
* Browser name: Google Chrome v.116.0.5845.112
* Operating System: Windows 10 64-bit

**Comment by AlekseyManetov** [comment]
Such behavior appears because react synthetic event propagation.
> An event fired from inside a portal will propagate to ancestors in the containing React tree, even if those elements are not ancestors in the DOM tree.

https://legacy.reactjs.org/docs/portals.html#event-bubbling-through-portals

Anyway, we can't make a silver bullet fix on our side(e.g. add `stopPropagation` in dropdown body by default), because it will broke expected event propagation flow on which someone can rely. 

But we have an approach how to not call `onClick` on parent nodes if this event was already fired by clickable children. You need to set '-clickable' selector on your clickable element(all our clickable components already have it) and then in row container we have a condition which not call row `onClick` if the event target was on node with '-clickable' selector.

I've a little bit changed your example, to illustrate the solution - https://codesandbox.io/s/uui-dropdown-propagated-click-from-body-to-target-issue-forked-tg4l2s?file=/Example.tsx
