### ISSUE TITLE
[Picker Input, LazyDataSource]: 'maximum call stack size exceeded' when flattenSearchResults=false and typing a search query

### ISSUE THREAD

**Issue by augustbright** [epam/UUI#1788]
## Steps to Reproduce
0. https://codesandbox.io/p/sandbox/uui-forked-vpvj9x
1. Given a lazy tree data multi picker, set `flattenSearchResults=false` for the datasource.
2. Then type a query in the search box.

## Actual result
An error is thrown: "Maximum call stack size exceeded"

## Expected result
Search query results in a list of items, represented in a tree-like structure

## Environment

* UUI version: 5.2.0
* Browser name: Chrome
* Operating System: macOS 14.1.1

*UPDATE*

Sorry for my mistake here.
The correct preconditions are:
```
flattenSearchResults=false
and datasource is lazy-tree
```

**Comment by Kuznietsov** [comment]
@augustbright, did you mean `flattenSearchResults=false` as it is mentioned in your example?

If you change `flattenSearchResults=false` to `flattenSearchResults=true` in your example, everything will work (flat list will be displayed).

If you want to search through a tree-like results, please, see the example: https://uui.epam.com/documents?id=pickerInput&mode=doc&skin=UUI&category=components#flatten_search_results_mode


Both examples are placed at that example.

**Comment by augustbright** [comment]
@Kuznietsov Sorry, seems that I've made a mistake in the issue title and description.

What I'm trying to achieve is make a **lazy** tree picker view, that would display search results as a **tree** structure. The codesandbox, that I provided in the description is actual though.

As for the examples, it seems to miss the case with a combination of lazy data-loading and tree-like searching.

Also, I've updated the description of this issue

**Comment by Kuznietsov** [comment]
First of all, we suggest using flatten search, because it makes lazy loading easier for users (users of the library).

But if you need to make your search tree-structured, we suggest the next flow:
- In LazyDataSource `api` it is required to handle three types of requests: query data without search, query data with search (top level), and query data by the parent. (See example here: https://github.com/epam/UUI/blob/023d6901333903d37a50364f10f9c969fa23f5b6/app/src/docs/_examples/pickerInput/LazyTreeSearch.example.tsx#L27C8-L27C8).
  - If a search is provided (while typing), dataSource will request top data;
  - If some top-level item has children, it will be unfolded and new data with search and parentId will be requested.
  That is how `lazy` tree-like search is achieved. 
- On the server side it is required to handle these three kinds of requests (query data without search, query top-level data with search, and query data by parentId and search). (See example here: https://github.com/epam/UUI/blob/023d6901333903d37a50364f10f9c969fa23f5b6/server/api/testDataApis.js#L109).
   In this example:
   - Data without search are queried from '/locations';
   - Data for tree-structured data is queried from 'locations/search-tree';
   - To make tree-structured search easier for devs, it can be helpful to pack children (found by search or those items, which are parents of a found item by search) into some object property (in the example, property `children` is used). And when LazyDataSource requests children by search and parentId, no request is needed, `api` will return data from `parent.children`.

WDYT, @augustbright, is it helpful for you?
