### ISSUE TITLE
[DatePicker]: Impossible to set the id attribute for the underlying input element

### ISSUE THREAD

**Issue by PMitrafanau** [epam/UUI#1812]
## Steps to Reproduce

1. Open the [sandbox](https://codesandbox.io/p/sandbox/crimson-wind-dcmpvt?file=%2Fsrc%2FExample.tsx)
2. Click on the "Test Date" label

## Actual result

Once the label is clicked, the dropdown is not opened. Reason: `rawProps.input` are passed to the container which wraps the input, not to the input itself thus making it impossible to set any props for the input, including the id.

## Expected result

Once the label is clicked, the dropdown is opened.

## Environment

* UUI version: latest
* Browser name: all
* Operating System: all

**Comment by AlekseyManetov** [comment]
@PMitrafanau Thanks for your issue. 
It's ok that `rawProps.input` are passed to the container which wraps the input, because according to the our rules `rawProps` should be passed to the component root node. But, to solve your case with label, I think we need to add separate `id` prop for the `DatePicker`, which will be passed directly to the `input` element.

**Comment by NatalliaAlieva** [comment]
Released in 5.5.0 ver.
