### ISSUE TITLE
[PIckerInput]: entered value clears when user put pointer in input repeatedly

### ISSUE THREAD

**Issue by mari-shakhanava** [epam/UUI#1822]
## Description (optional)

This issue is about disappearing entered value when repeated putting pointer in the input field.

 ## Steps to Reproduce

1. PickerInput with searchPosition='input' prop.
2. Start typing anything
3. After appearing values in dropdown put pointer back in the input

https://github.com/epam/UUI/assets/70166849/8bbb4d45-a2c5-4edf-9e03-167da7d6fb26

## Actual result

Entered value cleared

## Expected result

The entered text should stay unchanged. As is in PickerInput with searchPosition='body', so user can continue his search

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: latest
* Browser name: Chrome latest
* Operating System: Windows latest

**Comment by AlekseyManetov** [comment]
Such behavior isn't related to the search typing, it's happening because we are clearing search value by picker close and in your case click in toggler of already opened Picker leads to its closing. I'm not sure that can do something with it, because both features - 'Toggle opened state by toggler click' and 'Clear search after dropdown close' is an a core ux requirements of this component. Probably we need to discuss, whether we need to close picker by click in toggler? @DzmitryTrubchyk what do you think?
As a one more solution, I will recommend to use `searchPosition='body'` for majority of cases, because this pattern more clear and not so confused according to the UX.

**Comment by AlekseyManetov** [comment]
We've decided that we should not close body by click on toggler in case when searchPosition='input' and body is open now.

**Comment by DzmitryTrubchyk** [comment]
[like]  Dzmitry Trubchyk reacted to your message:
________________________________
