### ISSUE TITLE
[PickerList] Synchronize implementation with `PickerInput` body component

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#2031]
## Now

Right now, `PickerList` doesn't work like the list in the `PickerInput`' body. There are some issue that stop me from using it right now:
1. If sorting is not provided, the selected options are put at the top, and not selected ones are put after them, which means on every change the order will change too. It doesn't make sense by its own, but is even less suitable for cases, when options list is clearly determined and manually defined, and its order shouldn't be changed. This logic of changing the order is implemented [here](https://github.com/epam/UUI/blob/main/uui-components/src/pickers/hooks/usePickerList.ts#L153)
2. It doesn't support nesting/folding/grouping. If I provide `parentId` to an option's object, the option just disappears from UI

Currently, to achieve the intended behavior, it is necessary to use `DataTable` component with one column, which looks like a lot of unnecessary work, or just compose the rows manually using `FlexRow`, `Checkbox`, `IconButton` with chevron icons, etc.

## To Do

Make `PickerList` component work in absolutely the same way as the list in the `PickerInput`'s body does.

## Describe the solution you'd like

1. Move the `PickerInput`'s body component's logic to the `PickerList` component and depend on it, so that they stay in sync
2. Adjust the `DataTable` component's implementation, if needed

**Comment by AlekseyManetov** [comment]
Hi @vasilii-kovalev, the PickerList component is designed for a slightly different UX case and doesn't function the same way as PickerInput. Its primary use case is to provide a short preview list of selected or popular items, with the full list available in a modal window. This pattern is often used for side panel filtration in catalogs, for example on learn.epam.com.

> If sorting is not provided, the selected options are put at the top, and not selected ones are put after them, which means on every change the order will change too. It doesn't make sense by its own, but is even less suitable for cases, when options list is clearly determined and manually defined, and its order shouldn't be changed.

This is expected behavior, which is required for such kind of UX components. This behavior is intended to highlight already selected items and allows users to easily unselect them without opening the modal.

> It doesn't support nesting/folding/grouping. If I provide parentId to an option's object, the option just disappears from UI

Yes, this component does not support displaying tree structure, because it's impossible to display tree in the short view, which is designed to display only flat lists.


I guess, you concern about points below, because you you're attempting to use PickerList to display a selectable list like PickerInput but without a dropdown. It might be better to render a list of DataPickerRow for yourself. Here's an [example](https://codesandbox.io/p/sandbox/uui-forked-kkf36r?file=%2FExample.tsx%3A41%2C19). 
We also have an open issue to create documentation with examples for creating such trees: https://github.com/epam/UUI/issues/609

**Comment by vasilii-kovalev** [comment]
Thank you for the detailed explanation!
Closing the issue.
