### ISSUE TITLE
[Text] Set `primary` color as a default value in Loveship skin

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#2462]
## Now

The default value is `night700` (`#474a59`).

[Link to the source code](https://github.com/epam/UUI/blob/main/loveship/components/typography/Text.tsx#L21).

## To Do

1. Change default value to `primary` (`#303240`), because it is a primary (main) color, so the library users don't have to set it manually all the time
2. Change the comment [here](https://github.com/epam/UUI/blob/main/loveship/components/typography/Text.tsx#L9)
3. Check that the issue is fixed in both Light and Dark themes

We discussed it with @AlekseyManetov a while ago. We considered it will be a breaking change, but this project does make breaking changes in minor version already, so I don't think this change should wait for the next major version.

**Comment by vasilii-kovalev** [comment]
Please check if it makes sense to do it alongside with #2461.

**Comment by vasilii-kovalev** [comment]
Maybe it makes sense to just set `primary` color in `uu` or `uui-components` packages, because Vanilla Thunder and Electric skins already do that.

**Comment by AlekseyManetov** [comment]
Unfortunately, we can't change the current default value for skins, as it would be a significant breaking change for users who are already accustomed to that default. Changing default values is particularly challenging in the context of breaking changes because it doesn’t produce any errors in the code, leaving you unaware of the need to review and decide on the appropriate value.

Therefore, we recommend explicitly passing the 'primary' color if that’s what you need.
