### ISSUE TITLE
[Loveship][FlexRow]: remove additional margings

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#2581]
## Steps to Reproduce
1. open  https://uui.epam.com/documents?id=flexRow&mode=propsEditor&isSkin=true&category=flexItems 
2. select theme: loveship
3. select props: children: 'Text, TextInput, Button' and columnGap: 6

## Actual result
actual space between elements is 12px
![2024-10-24_10h56_08](https://github.com/user-attachments/assets/b935708c-35cb-4f74-a25e-0dfc6701a9a5)

## Expected result
space between elements is 6px

**Comment by vasilii-kovalev** [comment]
I can see that [default `spacing` values are defined here](https://github.com/epam/UUI/blob/main/loveship/components/layout/FlexItems/FlexRow.tsx).
`spacing` property has been deprecated:
* [Warning in development mode](https://github.com/epam/UUI/blob/main/uui/components/layout/FlexItems/FlexRow.tsx#L30-L34)
* [Release notes](https://github.com/epam/UUI/releases/tag/v5.7.0)

Does it make sense to remove the default values, if the property itself will be removed anyway?
P.S.: I'm not a part of the team, just a little [familiar with the topic](https://github.com/epam/UUI/issues/2034) 😊

**Comment by AlekseyManetov** [comment]
>Does it make sense to remove the default values, if the property itself will be removed anyway? Plus, it would be https://github.com/epam/UUI/issues/2034#issuecomment-1994575382.

I believe we should do it together with prop removing, because default value change would already be a breaking change itself.

The current situation is also problematic because user need to provide `spacing={ null }` along with `columnGap` to disable the warning and spacing default behavior. On the other hand, we want this change to be reviewed and managed by UUI clients, as it may require additional adjustments on the project side in some cases.

**Comment by AlekseyManetov** [comment]
Finally we've decided to replace default value from `spacing` to `columnGap` for loveship skin, with a small breaking change for corner case. Will release it in a next release - https://github.com/epam/UUI/commit/77c7ea210595e7bd5dae23fe683af0e8030e42a3.
* [FlexRow][Breaking Change]: Only for @epam/loveship package. Now spacing default value works based on columnGap props. It shouldn't affect general cases, but previous spacing implementation require additional hack when it was needed to add negative margin value for container to remove corner paddings in multiline case. Now this hack should be removed, since columnGap implementation doesn't produce such bug for multiline.

**Comment by NatalliaAlieva** [comment]
Released in 5.11.0 ver.
