### ISSUE TITLE
add a rawProps to Button

### ISSUE THREAD

**Issue by ZhannaL** [epam/UUI#32]
Add a rawProps to Button to be able to pass accessibility props like `aria-label` or other custom props like `data-testid`

**Comment by a4k** [comment]
Yes, I vote to add a `data-testid` to every UI component.

**Comment by jakobz** [comment]
I believe we need some consistend mechanism for all components to add aria-* and data-* attributes. We can then add support for this feature gradually for all components.

Points to consider:

1. API should be designed to not waste performance. Spreading the whole object to props is ok. Iterating thru all props to select only props needed is not. That's why we shouldn't go with something like this: <Button data-testid={ 123 } /> - because in this case we'd need to look for all data-attributes in the Button props to separate them from button's own props. That would be inefficient and would require too much error-prone magic.
2. We should consider using React typings - like ButtonHTMLAttributes. However, we need to check if there are all necessary attributes defined. Especially for data-* attributes, as such attributes can be correctly typed only in latest TypeScript versions.
TBD: check how data-* attributes are typed, especially in latest @types/react 
3. components usually has several wrappers, and it's unclear on which component to attach these attributes. E.g. TextInput contains top-level div, which wraps actual HTML input. Users would like to attach data-* attributes on top-level wrapper, and, probably, some aria-attributes to the underlying HTML Input. We need to design API to allow to attach props to both wrapper and input.

Currently, we have the following design in a few components:
<Anchor rawProps={{ data-testid: 123 }} /> // rawProps: HTMLAttributes<HTMLElement>

This design satisfies points 1 and 2. 

We can handle point 3 with an approach like this:
<TextInput rawProps={{ ... goes to wrapper }} inputRawProps={{ ... goes to HTML input }} />

This API would work, but I can't say I like it. I would like API to search for a more elegant design. Probably there are better ideas on props naming?

**Comment by jakobz** [comment]
I believe rawProps is ok for some corner-cases. However, test-id is not a corner-case - every other component in a project would have it. Probably we need to find a better approach for this particular case. Some ideas:

1. <Button data={{ testid: 'save' }} />
- this would have some performance impact, as we'd need to iterate Object.keys(props.data) to add 'data-' prefix. However, it looks more consise than with rawProps.

2. <Button test-id={{ 'save' }} /> 
- I mean we can make an exception to this very prop, and implement it explicitly. This prop would be spread across the whole code, and probably it desires this.

3. <Button id={{ 'save' }} /> or <Button cx={{ 'tst-save' }}
- I mean can we just use plain HTML ids or CSS classes to attach test scripts?

**Comment by a4k** [comment]
I think that we may use CSS classes to identify component on screen (for testing purposes). I'd like to find good idea to solve our issue (with API design and attributes). But there seems to be no better solution. Until it is found, we will use <Button cx={{ 'tst-save' }} />.

rawProps - could help to add some attributes to component, but it looks a little bit complicated.
