### ISSUE TITLE
When table has [add line] button and has no lines yet, I can't make it have only the button in the content area

### ISSUE THREAD

**Issue by vitali-paliakou** [epam/UUI#397]
# Expected Behavior

![image](https://user-images.githubusercontent.com/97738348/150361790-423a90f6-055b-4d01-b68d-8649e90ef2c9.png)

# Current Behavior

![image](https://user-images.githubusercontent.com/97738348/150361855-d03614c7-fcb2-4e86-906f-c2c769d9f231.png)
## Context

As I know, it's just a basic behavior to put this text placeholder / empty state in case there're no lines. But I don't need it because I already has a button.

**Comment by AlekseyManetov** [comment]
You can configure table empty state by `renderNoResultsBlock` prop in `DataTable`. For your case you need to pass function which will return nothing or your button, if you need it only in case when table have no rows. 
Also, based on your screenshots, you already have custom `renderNoResultsBlock` which passed from your side, because by default we have another empty state block. So you need to modify your `renderNoResultsBlock` implementation.
