### ISSUE TITLE
[VirtualList]: When expanding by clicking on any row, the component height is not recalculated

### ISSUE THREAD

**Issue by dsv-sergey** [epam/UUI#40]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

When expanding by clicking on a row, a scroll bar is expected to appear on the right, provided that the content exceeds the size of the container

# Current Behavior

When expanding on click, any row does not appear on the right of the scroll bar, provided that the content exceeds the size of the container

## Context

One possible solution is to trigger the 'estimatedHeight' recalculation in such situations
![image](https://user-images.githubusercontent.com/33173033/119983959-8673cd80-bfc9-11eb-8251-ce1ab171d0fb.png)

**Comment by jakobz** [comment]
I'd try another approach.

Currently, we position the visible section inside the scrolling section with position:absolute.
We can change this like this:
- position the visible section with margin-top: offset instead (here: https://github.com/epam/UUI/blob/main/uui-components/src/layout/VirtualList.tsx#L138 and remove 'position: absolute' here: https://github.com/epam/UUI/blob/main/uui-components/src/layout/VirtualList.scss#L32)
- set scrolling section height with min-height, instead of height (here: https://github.com/epam/UUI/blob/main/uui-components/src/layout/VirtualList.tsx#L138)

This way we always fit the content of the visible section, even if it get updated, and we haven't re-measured the new height for some reason (e.g. component updated on it's own, w/o re-rendering VirtualList).
