### ISSUE TITLE
Make Tooltip component based on Dropdown

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#402]
**Description**
Now `Tooltip` and `Dropdown` components works very similar, but has each own implementation and codebase. Also some functions only exist in `Dropdown` component, but missing in `Tooltip`, for example 'boundary' close mode.

**Describe the solution you'd like**
It will be good if we try to make `Tooltip` component base on `Dropdown`, so `Tooltip` will extend all `Dropdown` logic and only provide own render implementation and default props.

**Comment by alex9pro** [comment]
Additionally I'd like to ask pass `arrowProps` in Dropdown's renderDropdownBody method, as it is implemented in Tooltip. Because we have need to create Dropdown with arrow, and sometimes it is not working properly, when not enough space to drop bottom:

![image](https://user-images.githubusercontent.com/7101211/168813217-f8807f1f-4cef-48e8-901f-d3f2eb6f0812.png)

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0. Minor issues reported [here](https://github.com/epam/UUI/issues/1026).
