### ISSUE TITLE
On table rows, 3-dots button hides after I move cursor to dropdown menu (button only appears when I hover the row)

### ISSUE THREAD

**Issue by vitali-paliakou** [epam/UUI#404]
## Context

We use tables where every row has 3-dots button, which appears only when you hover on the row:
![image](https://user-images.githubusercontent.com/97738348/150597234-5457e2f0-b8a8-4a38-a63b-a8acaba02877.png)
When you click on this button, a dropdown menu appears. And when you move cursor to the menu, it leaves the row, it gets back to "rested" (not hovered) state, and 3-dots button disappears. And now you can see a dropdown menu without a button that has invoked it, which is confusing from UX perspective.

# Expected Behavior

![image](https://user-images.githubusercontent.com/97738348/150596736-1b6aa8ba-29c9-44fc-88bf-c909590c78be.png)

# Current Behavior

![image](https://user-images.githubusercontent.com/97738348/150596824-e023ac82-6440-46dc-8329-9c22f2a48d80.png)

**Comment by haresh1410** [comment]
Hi @vitali-paliakou to better debug this issue, can you please share a code sandbox link with this behavior.

**Comment by vitali-paliakou** [comment]
Hi @haresh1410. Sorry, but I'm a designer, not a developer — can't share a code sandbox link with you

**Comment by AlekseyManetov** [comment]
HI! I don't think that is bug of UUI, because you leave cursor from the row and it cause focus lost, it's default browser behavior. 
You can partially fixed this behavior by setting 3 dots button visibility based on  hover **or** if `DropdownMenu` is open state, by such logic if `DropdownMenu` is open button will be always visible, even if row lost his focus.

**Comment by vitali-paliakou** [comment]
It's fine not to highlight entire row when cursor leaves the row, but three dots icon shall remain visible when dropdown menu is visible — otherwise it looks like a dropdown menu without an element that invokes it. And that should be the basic behavior for such cases — that was discussed with UUI designers (Yaroslav Zinkov and Ilya Gorchakov).

So, it shouldn't be a custom thing to do, it's expected to be basic behavior for dropdown menus in tables.

**Comment by AlekseyManetov** [comment]
It can't be done as basic behavior in Table, because Table by itself don't render any content, render for each column provided from UUI users. Therefore, this button may or may not be in the table or will have different behavior, it can't be a part of the table. From another side `DropdownMenu` can be placed in anywhere - in table, panel or in any other contexts, with any variation of targets and target visibility, which also provided by user. 
So we can't make this a part of the UUI, because all this logic come from project side and not a part of our components. As a solution we can make such example of code on one of our demo, and share link to this example for developers if they will need to implement such behavior.

**Comment by vitali-paliakou** [comment]
That will work, I guess

I would say, in every case where the button that invokes a dropdown hides after you don't hover it (but dropdown menu is still visible), in expected behavior it shall remain visible. If it can't be done on a code level, maybe we should put it in the UUI guidelines for developers? @ilya-gorchakov-epam, what do you think?

**Comment by haresh1410** [comment]
@vitali-paliakou   As suggested by @AlekseyManetov  I have implemented the expected behavior as a example code here.
https://codesandbox.io/s/uui-forked-08nhwf?file=/Example.tsx

**Comment by haresh1410** [comment]
@vitali-paliakou @AlekseyManetov @ilya-gorchakov-epam can we close the bug if the above example code link is working with the expected behavior ? I can make changes in the example code if anything else is required.

**Comment by AlekseyManetov** [comment]
@haresh1410 Thanks for your contribution. In your codesandbox, a little bit different case: the 3 dots button is always visible, but @vitali-paliakou mentioned case when this button is appearing by row hover. 
You can gen example of this hove behavior on our Table [demo](https://uui.epam.com/demo?filter=undefined&id=table.), it a little bit different, but demonstrate haw button will appear on hover.

Also i think we don't need to have any hacks about saving row hover when dropdown is open, we just need to display 3 dots button when dropdown isOpen, we can make it just by adding additional class to this button when dropdown open:
`<Dropdown
              renderBody={() => renderDropdownBody()}
              renderTarget={(props) => { <Button cx={[css.dotsButton, props.isOpen && css.visibility]} /> }
/>`

Additionally, it will be good to such behavior on one of our doc example, not only in codesendox. For example you can try to implement such behavior for this table [example](https://uui.epam.com/documents?category=components&id=tables&mode=doc&skin=UUI4_promo#lazy_table)


PS: please use Button from UUI, instead of using HTML raw button.

**Comment by haresh1410** [comment]
Thanks @AlekseyManetov  for the detailed clarification.

I have implemented this behavior in this code sandbox link over the doc [example](https://uui.epam.com/documents?category=components&id=tables&mode=doc&skin=UUI4_promo#lazy_table)
https://codesandbox.io/s/uui-forked-zdsoyw?file=/Example.tsx

Let me know if there are any other actions required from my end :)

**Comment by AlekseyManetov** [comment]
Almost correct, you need to show button not on the cell hover but on all row hover. 
I have made some changes and already update our example and codesandbox. There is the correct one - https://codesandbox.io/s/f5dxkb?file=/Example.tsx
