### ISSUE TITLE
Resolve conflicting dependencies of draft and slate editors

### ISSUE THREAD

**Issue by gegorov** [epam/UUI#456]
**Description**
During installation of the packages i'm getting npm warnings about conflicting dependencies. 
![image](https://user-images.githubusercontent.com/13545473/154959126-cbfc8b32-c969-4368-b1f2-f01f341a9989.png)
![image](https://user-images.githubusercontent.com/13545473/154959220-ba580914-b24f-4a8e-850d-e84ed8c4308d.png)
![image](https://user-images.githubusercontent.com/13545473/154959284-8f8f7df4-9782-4031-ad97-63a3f3315d88.png)

**Describe the solution you'd like**
i would like to have nice npm output :) without conflict

**Comment by okrypets** [comment]
Hello. These warnings occur due to conflicts of external dependencies. 

I think they will be resolved after updating the slate version that is used under hood in uui-editor. This upgrade is already planed.

Warnings that occur during installation draft-rte is also related to conflicts of external dependencies. But there is no way to fix warnings for draft-rte  yet.
