### ISSUE TITLE
[PickerModal] add possibility to hide the search field

### ISSUE THREAD

**Issue by MSt1ch** [epam/UUI#474]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

I want to hide the search field on the PickerModal component. For instance through searchPosition="none" prop.

# Current Behavior

Currently it doesn't work.

* UUI version: Latest;
* Browser name: All;
* Operating System: All;

**Comment by AlekseyManetov** [comment]
We need to think over the design and UX for this solution, because besides search also we have 'Show only selected' toggle in this container.
@MSt1ch it will be nice, if designer from your project side can investigate it and provide design solution.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/14283670/160114438-98520d2b-c09c-4439-b442-2622b4fcf312.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/14283670/160114705-dbcf6912-e99a-48fd-85fd-b477079c1231.png">
