### ISSUE TITLE
Disabled LinkButton in 'promo' skin shouldn't respond to hover and pressing

### ISSUE THREAD

**Issue by dsv-sergey** [epam/UUI#56]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Disabled LinkButton in 'promo' skin shouldn't respond to hover and pressing

# Current Behavior

LinkButton reacts to hover and pressing

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. Provide screenshots or minimal code snippet where appropriate.

![image](https://user-images.githubusercontent.com/33173033/121660013-897fbb00-caab-11eb-8600-6de152a611e4.png)

**Comment by 0PabloTapia** [comment]
is there any environment variables to set this project on local environment, i keep gettin unexpected token . while trying to run it

**Comment by AlekseyManetov** [comment]
@0PabloTapia no any variables needed to start the project, just these steps - https://github.com/epam/UUI#development

Could you please describe which error do you have?

**Comment by 0PabloTapia** [comment]
this happens when i run it from the UUI folder
![Captura de pantalla de 2021-06-16 11-40-15](https://user-images.githubusercontent.com/52087953/122250598-ca0a7a80-ce97-11eb-8a07-6261a60e9bb9.png)

this happens when i run the command inside the uui folder as the doc implies

![Captura de pantalla de 2021-06-16 11-44-16](https://user-images.githubusercontent.com/52087953/122251124-3d13f100-ce98-11eb-9d72-9482f2c686f1.png)

thats because there is actually no start script on the package.json, tried to add it myself but then again i get this

![Captura de pantalla de 2021-06-16 11-46-40](https://user-images.githubusercontent.com/52087953/122251503-8feda880-ce98-11eb-878a-2bb071e1d46d.png)

**Comment by okrypets** [comment]
@0PabloTapia 
We have corrected the description of how to start the application locally. Please try again
