### ISSUE TITLE
Add possibility to use rawProps with list of components below

### ISSUE THREAD

**Issue by AlekseyManetov** [epam/UUI#641]
### Discussed in https://github.com/epam/UUI/discussions/636

<div type='discussions-op-text'>

<sup>Originally posted by **NatatkaValikowsky** July 26, 2022</sup>
Hi! We need to add HTML attributes to all components in our project to use it in auto tests.

In this components we cannot use rawProps property:
- Data Tables
- File Upload
- Paginator
- Picker List
- Rating
- Slider Rating
- Text Placeholder
- Time Picker

Do you plan to add rawProps to this components? How we can help to deal with it?</div>

**Comment by 13IEZ** [comment]
Added rawProps to all components except DataTable because DataTable needs a container node that can receive rawProps, but DataTable doesn't because DataTable  returns React.Fragment

But you can pass your props to the DataTable wrapper node like in the example - https://codesandbox.io/s/uui-forked-3uvb0o?file=/Example.tsx
