### ISSUE TITLE
[Picker Input lazy tree] Parent is added to amount of child

### ISSUE THREAD

**Issue by TanyaNovik** [epam/UUI#713]
# Description

## Steps to Reproduce

1. open [picker input lazy tree](https://uui.epam.com/documents?category=components&id=pickerInput&mode=doc&skin=UUI4_promo#lazy_tree) component
2. open "Oceania"
3.  select "Tuvalu"

## Actual result
"Tuvalu" is added to amount of city.
![image](https://user-images.githubusercontent.com/15855493/192256571-b8da57aa-4680-418d-9875-c246d24f0358.png)

## Expected result

"Tuvalu" is not added to amount of city. Only "Funafuti" is counted.

# Environment

**Comment by AlekseyManetov** [comment]
Hi, this is expected behavior with `cascadeSelection={ true }` prop, when you select parent also all his children are chosen too. For example if you don't won't to save it, you can just filter parent items from selected value array before sent it to api.

**Comment by TanyaNovik** [comment]
In our application we want that parent(region) isn't counted with child(country). we need to count only child(country). It's from our application: 
![Screenshot_18](https://user-images.githubusercontent.com/15855493/192513404-b673c7ab-28fc-4210-a307-76ee61b30099.png)
I can add one more parameter to count or not parents with children.

**Comment by AlekseyManetov** [comment]
Hi, it's not a bug, parent also goes to the selection, if you check picker value you will see 8 items. By our PickerInput logic, parent it's independent items which also selected, and it's expected behavior to count it in PickerToggler. The behavior which you want a little bit different, in such way we need to 'virtual' select parent but don't add him into value, it can be done by some prop setting, for example addParentToSelection, but for now it's hard to implement it with current PickerInput code approach. Do you have a problem only with counting this item in toggler or you also need to remove parent from picker value? We can try to find some workaround for your.

**Comment by TanyaNovik** [comment]
Hello, yes, we want to select parent but not count it with child. We can add addParentToSelection which will be true or false and in getCaption count only child if addParentToSelection = false using childCount parameter in props.selection array.

**Comment by AlekseyManetov** [comment]
For your case you can provide your own renderToggler callback, where you need to pass to the seletion array without parents:
`                    renderToggler={ (props) => <PickerToggler { ...props } selection={removerParents(selection)} /> }`
