### ISSUE TITLE
[RTE] Copy-pasted text inserted without some formatting options from One note app

### ISSUE THREAD

**Issue by ialeksandrovich** [epam/UUI#716]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Description

## Steps to Reproduce

1. Open Rich Text Editor
2. Copy text with bullets and links from One note app
3. Insert text in Rich Text Editor

## Actual result

Tab formatting with bullet and links  missed during pasting

## Environment

* UUI version: 4.8.5
* Browser name: Chrome
* Operating System: Windows

**Comment by AlekseyManetov** [comment]
Hi, we have support of pasting html structure into our editor, if One note app return html it will work, but i guess there may be some issues. Basically we don't provide support for copy/past content from any app which use rich text markup, because don't have capacity to support and fix issues for each app. Additionally we can't affect on format which app will return for us, it can be fully incompatible with our.  So it's recommended to create content directly in UUI RTE and don't rely that you content from another app will be copied without any issues.
