### ISSUE TITLE
[Button] border color issue

### ISSUE THREAD

**Issue by mikzakh** [epam/UUI#808]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

Button has wrong border color on Samsung devices.

## Steps to Reproduce

1. Go to a real device cloud (https://app.mobitru.com/)
2. Select Samsung Galaxy A12 device
3. Open [page](https://uui.epam.com/documents?category=components&id=button&mode=propsEditor&skin=UUI3_loveship) from documentation
4. Check button border color

## Actual result

Button border has incorrect color

![button-border](https://user-images.githubusercontent.com/97105597/199686815-7baebf55-30cb-4139-a40d-5e4b44613d94.png)

## Expected result

Button border has blue color

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.8.5
* Browser name: Chrome
* Operating System: Android

**Comment by NatalliaAlieva** [comment]
Hello.
This bug is reproduced only on mobile farm for Samsung A12. I rechecked its reproduction on some other devices - there was no such behavior. Also the bug was tested on physical devices (iPhone 13 pro, Samsung S21, Xiaomi Mi 10T lite) and it was not reproduced on them as well. 
If the bug is still relevant for you, feel free to reopen it by adding a list c more devices on which it is reproduced.
