### ISSUE TITLE
[Notifications]: can't show several notification in a row

### ISSUE THREAD

**Issue by blackymax** [epam/UUI#841]
Now
Here is an example, where we could see, that if we need to show 2 or more notifications in a row (when mapping an array of errors),
we get all notifications, but after the first one, rest of them are hidden
https://codesandbox.io/s/uui-forked-6bttvo?file=/Example.tsx

To Do
Check notifications 'show' method

**Comment by dzevakov** [comment]
Changed reference binding. Since when rendering multiple components, you need a separate corresponding reference for each notification. In the previous version, there was a single reference to the element to which all notices were attached. As a result, changes to the assignments of the CSSTransition classes that control the entry/exit animation of the notification components failed.

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
