### ISSUE TITLE
[Docs] Add documentation for Table-related components and React Hooks

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#940]
## Description

Previously, it was possible to open the tables-related components documentation. Though it wasn't comprehensive enough, at least there was a part of the `DataTable` component's API presented. Now, that element in the side menu is not clickable, and only [Editable Table](https://uui.epam.com/documents?id=editableTables&mode=doc&skin=UUI4_promo&category=tables) page is available, though it doesn't have any API at all.

## Describe the solution you'd like

1. Make "Data Tables" element in the side menu clickable. It should contain the main information about the tables-related API, and the "Editable Table" page should contain information about that specific example of the table (editable). If the amount of that specific information is little, maybe it makes sense to get rid of this page at all, and move that single example to the "Data Tables" page
2. Describe the API of all the components (table, rows, cells, etc.) and React Hooks (`useArrayDataSource`, `useLazyDataSource`, etc., including the API of the results, so that, for example, `dataSource.useView` is also described) on the "Data Tables" page

**Comment by AlekseyManetov** [comment]
Recently we restructured our DataTable documentation, we divided it for several pages, because it became too mach information and examples for one page. Now you can expand Data Tables section and find tables related documentation divided by topics. General information can be found in Overview topic.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/14283670/212054637-ab2ac929-fdc5-44e8-8f91-e3316074e67a.png">

Also we have documentation improvements in our roadmap for this year, which will include Data Table related staff documentation also.
