### ISSUE TITLE
NumericInput doesn't update value on key press

### ISSUE THREAD

**Issue by borishere** [epam/UUI#97]
# Expected Behavior

**NumericInput** should update value state immediately after key press in order we could validate it, etc.

# Current Behavior

When we enter value by keyboard, state changes only when we click outside of current input.

## Steps to Reproduce

1. type number in **NumericInput**
2. check that **onValueChange** didn't trigger
3. you get it...

**Comment by AlekseyManetov** [comment]
Hi. Current behavior is correct, we call onValueChange on input blur, if we will do it on input value change it will cause weird side effects. 
For example: if we pass min={ 11 } and type '15' in input, then you can't remove '5' digit and type anything else, because when you delete '5', value became '1' and it's not valid. 
Also it will be strange for user, when he type anything and input don't response, because he type some invalid value.

**Comment by borishere** [comment]
Thanks for your explanation. 
The behavior is clear for me now 😊
